#!/usr/bin/env bash

#MISE description="Create tarballs for oclif CLI packages"

set -euo pipefail

oclif pack tarballs \
    --targets "darwin-x64,darwin-arm64" \
    --no-xz

# oclif pack tarballs \
#     --targets "linux-x64,linux-arm64,darwin-x64,darwin-arm64" \
#     --no-xz
